import { CriterialType, EventPeriod, ExperienceItemProps } from '@/utils/types'

export const jobData = [
  {
    title: 'Senior Data Analyst',
    postedAgo: '100 days ago',
    positionsLeft: 3,
    applications: 123,
    interviewed: 40,
    rejected: 33,
    feedbackPending: 7,
    offered: 2,
  },
  {
    title: 'Junior Data Analyst',
    postedAgo: '78 days ago',
    positionsLeft: 7,
    applications: 567,
    interviewed: 22,
    rejected: 20,
    feedbackPending: 2,
    offered: 4,
  },
  {
    title: 'Product Designer',
    postedAgo: '56 days ago',
    positionsLeft: 2,
    applications: 201,
    interviewed: 32,
    rejected: 18,
    feedbackPending: 14,
    offered: 0,
  },
  {
    title: 'Java Developer',
    postedAgo: '46 days ago',
    positionsLeft: 5,
    applications: 231,
    interviewed: 23,
    rejected: 10,
    feedbackPending: 13,
    offered: 3,
  },
  {
    title: 'Product Manager',
    postedAgo: '13 days ago',
    positionsLeft: 3,
    applications: 67,
    interviewed: 41,
    rejected: 22,
    feedbackPending: 19,
    offered: 1,
  },
]

export const candidatesData = [
  {
    name: 'Gakire Clement',
    title: 'Sr. Software Developer',
    onboardedOn: 'Jul 3, 2023',
    training: '06/10',
    documentation: '06/10',
    supervisor: 'Not allocated',
    project: 'Not Allocated',
  },
  {
    name: 'Mutoni Angel',
    title: 'Sr. Product Designer',
    onboardedOn: 'Jul 9, 2023',
    training: '02/8',
    documentation: '06/10',
    supervisor: 'John Doe',
    project: 'Respilon',
  },
  {
    name: 'Hirwa Fabienne',
    title: 'Product Lead',
    onboardedOn: 'Mar 20, 2023',
    training: '01/5',
    documentation: '06/10',
    supervisor: 'Not allocated',
    project: 'Not Allocated',
  },
  {
    name: 'Ntwari Amri',
    title: 'Sr. Java Developer',
    onboardedOn: 'Aug 18, 2023',
    training: '07/10',
    documentation: '06/10',
    supervisor: 'John Doe',
    project: 'Respilon',
  },
  {
    name: 'Kalisa John',
    title: 'Sr. Software Developer',
    onboardedOn: 'Sep 22, 2023',
    training: '06/10',
    documentation: '06/10',
    supervisor: 'Not allocated',
    project: 'Not Allocated',
  },
]

export const onboardingsData = [
  {
    name: 'Gakire Clement',
    role: 'UX Researcher',
    appliedOn: 'Jul 3, 2023',
    interviewRound: '06/10',
    assignedTo: 'Not allocated',
    score: 80,
  },
  {
    name: 'Mutoni Angel',
    role: 'UX Designer',
    appliedOn: 'Jul 3, 2023',
    interviewRound: '06/10',
    assignedTo: 'Raghav Menon',
    score: 33,
  },
  {
    name: 'Hirwa Fabienne',
    role: 'UI Designer',
    appliedOn: 'Jul 3, 2023',
    interviewRound: '06/10',
    assignedTo: 'Not allocated',
    score: 66,
  },
  {
    name: 'Ntwari Amri',
    role: 'Jr. Data Analyst',
    appliedOn: 'Jul 3, 2023',
    interviewRound: '06/10',
    assignedTo: 'Raghav Menon',
    score: 55,
  },
  {
    name: 'Kalisa John',
    role: 'Sr. Data Analyst',
    appliedOn: 'Jul 3, 2023',
    interviewRound: '06/10',
    assignedTo: 'Not allocated',
    score: 78,
  },
]

export const eventPeriods: EventPeriod[] = [
  {
    period: 'Today',
    events: [
      {
        startTime: '3:15',
        endTime: '3:45',
        name: 'Mini Soman',
        position: 'Mean stack developer',
        phase: '4th phase interview',
        active: false,
      },
      {
        startTime: '10:00',
        endTime: '10:30',
        name: 'Sarah Wilson',
        position: 'Frontend Developer',
        phase: '2nd phase screening',
        active: false,
      },
      {
        startTime: '10:00',
        endTime: '10:45',
        name: 'Alex Chen',
        position: 'DevOps Engineer',
        phase: 'Technical assessment',
        active: false,
      },
      {
        startTime: '10:00',
        endTime: '11:00',
        name: 'Emily Rodriguez',
        position: 'Product Manager',
        phase: 'Final interview',
        active: true,
      },
    ],
  },
  {
    period: 'Tomorrow',
    events: [
      {
        startTime: '3:15',
        endTime: '4:00',
        name: 'David Thompson',
        position: 'Backend Engineer',
        phase: '1st phase interview',
        active: false,
      },
      {
        startTime: '10:00',
        endTime: '10:30',
        name: 'Lisa Park',
        position: 'UX Designer',
        phase: 'Portfolio review',
        active: true,
      },
      {
        startTime: '10:00',
        endTime: '11:15',
        name: 'Michael Kumar',
        position: 'Data Scientist',
        phase: '3rd phase interview',
        active: false,
      },
      {
        startTime: '10:00',
        endTime: '10:45',
        name: 'Rachel Green',
        position: 'QA Engineer',
        phase: '2nd phase screening',
        active: false,
      },
    ],
  },
  {
    period: 'This Week',
    events: [
      {
        startTime: '9:00',
        endTime: '9:30',
        name: 'James Wilson',
        position: 'Mobile Developer',
        phase: 'Technical interview',
        active: false,
      },
      {
        startTime: '11:00',
        endTime: '11:45',
        name: 'Amanda Foster',
        position: 'Scrum Master',
        phase: 'Final round',
        active: false,
      },
      {
        startTime: '2:30',
        endTime: '3:15',
        name: 'Kevin Lee',
        position: 'Cloud Architect',
        phase: '4th phase interview',
        active: false,
      },
      {
        startTime: '4:00',
        endTime: '4:30',
        name: 'Sophie Martinez',
        position: 'Security Engineer',
        phase: '1st phase screening',
        active: false,
      },
      {
        startTime: '10:15',
        endTime: '11:00',
        name: 'Ryan Davis',
        position: 'AI Engineer',
        phase: '2nd phase interview',
        active: false,
      },

      {
        startTime: '9:00',
        endTime: '9:30',
        name: 'James Wilson',
        position: 'Mobile Developer',
        phase: 'Technical interview',
        active: false,
      },
      {
        startTime: '11:00',
        endTime: '11:45',
        name: 'Amanda Foster',
        position: 'Scrum Master',
        phase: 'Final round',
        active: false,
      },
      {
        startTime: '2:30',
        endTime: '3:15',
        name: 'Kevin Lee',
        position: 'Cloud Architect',
        phase: '4th phase interview',
        active: false,
      },

      {
        startTime: '4:00',
        endTime: '4:30',
        name: 'Sophie Martinez',
        position: 'Security Engineer',
        phase: '1st phase screening',
        active: false,
      },
      {
        startTime: '10:15',
        endTime: '11:00',
        name: 'Ryan Davis',
        position: 'AI Engineer',
        phase: '2nd phase interview',
        active: false,
      },
    ],
  },
]

export const lastExperience: ExperienceItemProps[] = [
  {
    position: 'Senior Data Analyst',
    periodTime: 'May 2021 - Present',
    workDescription: [
      'Data Exploration and Analysis: They perform exploratory data analysis to uncover insights, trends, and patterns in the data, often using statistical and visualisation techniques.',
      'Data Cleaning and Preprocessing: Data analysts are responsible for cleaning and preparing raw renewable data to ensure its accuracy and reliability for analysis.',
      'Reporting and Communication: Data analysts communicate their findings through reports, dashboards, and presentations to help stakeholders make informed decisions based on the data-driven insights.',
    ],
  },

  {
    position: 'Junior Data Analyst',
    periodTime: 'May 2020 - May 2021',
    workDescription: [
      'Data Exploration and Analysis: They perform exploratory data analysis to uncover insights, trends, and patterns in the data, often using statistical and visualisation techniques.',
      'Data Cleaning and Preprocessing: Data analysts are responsible for cleaning and preparing raw renewable data to ensure its accuracy and reliability for analysis.',
      'Reporting and Communication: Data analysts communicate their findings through reports, dashboards, and presentations to help stakeholders make informed decisions based on the data-driven insights.',
    ],
  },
]

export const criterials: CriterialType[] = [
  { title: 'Qualifications and skills match', checked: true },
  { title: 'Experience Rlevance', checked: true },
  { title: 'Education', checked: true },
  { title: 'Keywords Match', checked: false },
  { title: 'Years of Experience', checked: true },
  { title: 'Job Hopping', checked: false },
  { title: 'Cultural Fit', checked: true },
  { title: 'Interview Performance', checked: false },
  { title: 'References', checked: true },
  { title: 'Additional Factors', checked: true },
]
