import { CriterialType, EventPeriod, ExperienceItemProps } from '@/utils/types'
import { InterviewStatus, Status } from '@prisma/client'

export const jobData = [
  {
    title: 'Senior Data Analyst',
    postedDate: '100 days ago',
    openings: 3,
    applicantsCount: 123,
    interviewed: 40,
    rejected: 33,
    feedbackPending: 7,
    offered: 2,
  },
  {
    title: 'Junior Data Analyst',
    postedDate: '78 days ago',
    positionsLeft: 7,
    applications: 567,
    interviewed: 22,
    rejected: 20,
    feedbackPending: 2,
    offered: 4,
  },
  {
    title: 'Product Designer',
    postedDate: '56 days ago',
    positionsLeft: 2,
    applications: 201,
    interviewed: 32,
    rejected: 18,
    feedbackPending: 14,
    offered: 0,
  },
  {
    title: 'Java Developer',
    postedDate: '46 days ago',
    positionsLeft: 5,
    applications: 231,
    interviewed: 23,
    rejected: 10,
    feedbackPending: 13,
    offered: 3,
  },
  {
    title: 'Product Manager',
    postedDate: '13 days ago',
    positionsLeft: 3,
    applications: 67,
    interviewed: 41,
    rejected: 22,
    feedbackPending: 19,
    offered: 1,
  },
]

export const candidatesData = [
  {
    name: 'Gakire Clement',
    email: 'gakire.clement@company.com', // Added email (required)
    phone: '+250 788 123 456', // Added phone
    position: 'Sr. Software Developer',
    experience: 5, // Added experience (required)
    skills: ['JavaScript', 'TypeScript', 'React', 'Node.js'], // Added skills
    status: 'Hired' as Status, // Mapped from onboarded status
    resume: 'https://example.com/resume/gakire-clement.pdf',
    notes: 'Experienced developer with strong technical skills',
    supervisor: 'paccy',
    documentation: '06/10',
    project: 'Not Allocated',
    training: '06/10',
    interviewStatus: 'Completed' as InterviewStatus,
    expectedSalary: 80000,
    currentSalary: 75000,
    noticePeriod: '30 days',
    location: 'Kigali, Rwanda',
    source: 'LinkedIn',
    onboardedOn: new Date('2023-07-03'), // Converting the date
  },
  {
    name: 'Mutoni Angel',
    email: 'mutoni.angel@company.com',
    phone: '+250 788 234 567',
    position: 'Sr. Product Designer',
    experience: 4,
    skills: ['Figma', 'Adobe XD', 'UI/UX Design', 'Prototyping'],
    status: 'Hired' as Status,
    resume: 'https://example.com/resume/mutoni-angel.pdf',
    notes: 'Creative designer with excellent portfolio',
    supervisor: 'mashami',
    documentation: '06/10',
    project: 'Respilon',
    training: '02/8',
    interviewStatus: 'Completed' as InterviewStatus,
    expectedSalary: 70000,
    currentSalary: 65000,
    noticePeriod: '30 days',
    location: 'Kigali, Rwanda',
    source: 'Referral',
    onboardedOn: new Date('2023-07-09'),
  },
  {
    name: 'Hirwa Fabienne',
    email: 'hirwa.fabienne@company.com',
    phone: '+250 788 345 678',
    position: 'Product Lead',
    experience: 6,
    skills: ['Product Management', 'Strategy', 'Analytics', 'Leadership'],
    status: 'Hired' as Status,
    resume: 'https://example.com/resume/hirwa-fabienne.pdf',
    notes: 'Strong leadership skills and product vision',
    supervisor: 'Not allocated',
    documentation: '06/10',
    project: 'Not Allocated',
    training: '01/5',
    interviewStatus: 'Completed' as InterviewStatus,
    expectedSalary: 90000,
    currentSalary: 85000,
    noticePeriod: '45 days',
    location: 'Kigali, Rwanda',
    source: 'Company Website',
    onboardedOn: new Date('2023-03-20'),
  },
  {
    name: 'Ntwari Amri',
    email: 'ntwari.amri@company.com',
    phone: '+250 788 456 789',
    position: 'Sr. Java Developer',
    experience: 7,
    skills: ['Java', 'Spring Boot', 'Microservices', 'Docker'],
    status: 'Hired' as Status,
    resume: 'https://example.com/resume/ntwari-amri.pdf',
    notes: 'Senior developer with strong Java expertise',
    supervisor: 'John Doe',
    documentation: '06/10',
    project: 'Respilon',
    training: '07/10',
    interviewStatus: 'Completed' as InterviewStatus,
    expectedSalary: 85000,
    currentSalary: 80000,
    noticePeriod: '30 days',
    location: 'Kigali, Rwanda',
    source: 'GitHub',
    onboardedOn: new Date('2023-08-18'),
  },
  {
    name: 'Kalisa John',
    email: 'kalisa.john@company.com',
    phone: '+250 788 567 890',
    position: 'Sr. Software Developer',
    experience: 5,
    skills: ['Python', 'Django', 'React', 'PostgreSQL'],
    status: 'Hired' as Status,
    resume: 'https://example.com/resume/kalisa-john.pdf',
    notes: 'Full-stack developer with Python expertise',
    supervisor: 'Not allocated',
    documentation: '06/10',
    project: 'Not Allocated',
    training: '06/10',
    interviewStatus: 'Completed' as InterviewStatus,
    expectedSalary: 78000,
    currentSalary: 72000,
    noticePeriod: '30 days',
    location: 'Kigali, Rwanda',
    source: 'Stack Overflow',
    onboardedOn: new Date('2023-09-22'),
  },
]

export const onboardingsData = [
  {
    name: 'Gakire Clement',
    role: 'UX Researcher',
    appliedOn: 'Jul 3, 2023',
    interviewRound: '06/10',
    assignedTo: 'Not allocated',
    score: 80,
  },
  {
    name: 'Mutoni Angel',
    role: 'UX Designer',
    appliedOn: 'Jul 3, 2023',
    interviewRound: '06/10',
    assignedTo: 'Raghav Menon',
    score: 33,
  },
  {
    name: 'Hirwa Fabienne',
    role: 'UI Designer',
    appliedOn: 'Jul 3, 2023',
    interviewRound: '06/10',
    assignedTo: 'Not allocated',
    score: 66,
  },
  {
    name: 'Ntwari Amri',
    role: 'Jr. Data Analyst',
    appliedOn: 'Jul 3, 2023',
    interviewRound: '06/10',
    assignedTo: 'Raghav Menon',
    score: 55,
  },
  {
    name: 'Kalisa John',
    role: 'Sr. Data Analyst',
    appliedOn: 'Jul 3, 2023',
    interviewRound: '06/10',
    assignedTo: 'Not allocated',
    score: 78,
  },
]

export const eventPeriods: EventPeriod[] = [
  {
    period: 'Today',
    events: [
      {
        startTime: '3:15',
        endTime: '3:45',
        name: 'Mini Soman',
        position: 'Mean stack developer',
        phase: '4th phase interview',
        active: false,
      },
      {
        startTime: '10:00',
        endTime: '10:30',
        name: 'Sarah Wilson',
        position: 'Frontend Developer',
        phase: '2nd phase screening',
        active: false,
      },
      {
        startTime: '10:00',
        endTime: '10:45',
        name: 'Alex Chen',
        position: 'DevOps Engineer',
        phase: 'Technical assessment',
        active: false,
      },
      {
        startTime: '10:00',
        endTime: '11:00',
        name: 'Emily Rodriguez',
        position: 'Product Manager',
        phase: 'Final interview',
        active: true,
      },
    ],
  },
  {
    period: 'Tomorrow',
    events: [
      {
        startTime: '3:15',
        endTime: '4:00',
        name: 'David Thompson',
        position: 'Backend Engineer',
        phase: '1st phase interview',
        active: false,
      },
      {
        startTime: '10:00',
        endTime: '10:30',
        name: 'Lisa Park',
        position: 'UX Designer',
        phase: 'Portfolio review',
        active: true,
      },
      {
        startTime: '10:00',
        endTime: '11:15',
        name: 'Michael Kumar',
        position: 'Data Scientist',
        phase: '3rd phase interview',
        active: false,
      },
      {
        startTime: '10:00',
        endTime: '10:45',
        name: 'Rachel Green',
        position: 'QA Engineer',
        phase: '2nd phase screening',
        active: false,
      },
    ],
  },
  {
    period: 'This Week',
    events: [
      {
        startTime: '9:00',
        endTime: '9:30',
        name: 'James Wilson',
        position: 'Mobile Developer',
        phase: 'Technical interview',
        active: false,
      },
      {
        startTime: '11:00',
        endTime: '11:45',
        name: 'Amanda Foster',
        position: 'Scrum Master',
        phase: 'Final round',
        active: false,
      },
      {
        startTime: '2:30',
        endTime: '3:15',
        name: 'Kevin Lee',
        position: 'Cloud Architect',
        phase: '4th phase interview',
        active: false,
      },
      {
        startTime: '4:00',
        endTime: '4:30',
        name: 'Sophie Martinez',
        position: 'Security Engineer',
        phase: '1st phase screening',
        active: false,
      },
      {
        startTime: '10:15',
        endTime: '11:00',
        name: 'Ryan Davis',
        position: 'AI Engineer',
        phase: '2nd phase interview',
        active: false,
      },

      {
        startTime: '9:00',
        endTime: '9:30',
        name: 'James Wilson',
        position: 'Mobile Developer',
        phase: 'Technical interview',
        active: false,
      },
      {
        startTime: '11:00',
        endTime: '11:45',
        name: 'Amanda Foster',
        position: 'Scrum Master',
        phase: 'Final round',
        active: false,
      },
      {
        startTime: '2:30',
        endTime: '3:15',
        name: 'Kevin Lee',
        position: 'Cloud Architect',
        phase: '4th phase interview',
        active: false,
      },

      {
        startTime: '4:00',
        endTime: '4:30',
        name: 'Sophie Martinez',
        position: 'Security Engineer',
        phase: '1st phase screening',
        active: false,
      },
      {
        startTime: '10:15',
        endTime: '11:00',
        name: 'Ryan Davis',
        position: 'AI Engineer',
        phase: '2nd phase interview',
        active: false,
      },
    ],
  },
]

export const lastExperience: ExperienceItemProps[] = [
  {
    position: 'Senior Data Analyst',
    periodTime: 'May 2021 - Present',
    workDescription: [
      'Data Exploration and Analysis: They perform exploratory data analysis to uncover insights, trends, and patterns in the data, often using statistical and visualisation techniques.',
      'Data Cleaning and Preprocessing: Data analysts are responsible for cleaning and preparing raw renewable data to ensure its accuracy and reliability for analysis.',
      'Reporting and Communication: Data analysts communicate their findings through reports, dashboards, and presentations to help stakeholders make informed decisions based on the data-driven insights.',
    ],
  },

  {
    position: 'Junior Data Analyst',
    periodTime: 'May 2020 - May 2021',
    workDescription: [
      'Data Exploration and Analysis: They perform exploratory data analysis to uncover insights, trends, and patterns in the data, often using statistical and visualisation techniques.',
      'Data Cleaning and Preprocessing: Data analysts are responsible for cleaning and preparing raw renewable data to ensure its accuracy and reliability for analysis.',
      'Reporting and Communication: Data analysts communicate their findings through reports, dashboards, and presentations to help stakeholders make informed decisions based on the data-driven insights.',
    ],
  },
]

export const criterials: CriterialType[] = [
  { title: 'Qualifications and skills match', checked: true },
  { title: 'Experience Rlevance', checked: true },
  { title: 'Education', checked: true },
  { title: 'Keywords Match', checked: false },
  { title: 'Years of Experience', checked: true },
  { title: 'Job Hopping', checked: false },
  { title: 'Cultural Fit', checked: true },
  { title: 'Interview Performance', checked: false },
  { title: 'References', checked: true },
  { title: 'Additional Factors', checked: true },
]
